version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install npm@latest -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run generate
artifacts:
  base-directory: dist/
  files:
    - '**/*'