version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i npm@latest -g
      - npm install nuxt
  pre_build:
    commands:
      echo Pre_build Phase
      - npm install
  build:
    commands:
      echo Build Phase
      - npm run build
      - npm run generate
artifacts:
  base-directory: dist
  files:
    - '**/*'